"""empty message

Revision ID: 2123097085af
Revises: 1c8c183b4cd9
Create Date: 2016-05-08 21:57:56.357430

"""

# revision identifiers, used by Alembic.
revision = '2123097085af'
down_revision = '1c8c183b4cd9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'courses_search_search_id_fkey', 'courses_search', type_='foreignkey')
    op.drop_constraint(u'courses_search_course_id_fkey', 'courses_search', type_='foreignkey')
    op.create_foreign_key(None, 'courses_search', 'courses', ['course_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'courses_search', 'search', ['search_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(u'courses_tags_course_id_fkey', 'courses_tags', type_='foreignkey')
    op.drop_constraint(u'courses_tags_tag_id_fkey', 'courses_tags', type_='foreignkey')
    op.create_foreign_key(None, 'courses_tags', 'courses', ['course_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'courses_tags', 'tags', ['tag_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(u'tags_search_tag_id_fkey', 'tags_search', type_='foreignkey')
    op.drop_constraint(u'tags_search_search_id_fkey', 'tags_search', type_='foreignkey')
    op.create_foreign_key(None, 'tags_search', 'search', ['search_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'tags_search', 'tags', ['tag_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(u'user_comment_like_user_id_fkey', 'user_comment_like', type_='foreignkey')
    op.drop_constraint(u'user_comment_like_comment_id_fkey', 'user_comment_like', type_='foreignkey')
    op.create_foreign_key(None, 'user_comment_like', 'comments', ['comment_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_comment_like', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(u'user_like_course_id_fkey', 'user_like', type_='foreignkey')
    op.drop_constraint(u'user_like_user_id_fkey', 'user_like', type_='foreignkey')
    op.create_foreign_key(None, 'user_like', 'courses', ['course_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_like', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(u'user_tips_like_user_id_fkey', 'user_tips_like', type_='foreignkey')
    op.drop_constraint(u'user_tips_like_tips_id_fkey', 'user_tips_like', type_='foreignkey')
    op.create_foreign_key(None, 'user_tips_like', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_tips_like', 'tips', ['tips_id'], ['id'], ondelete='CASCADE')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_tips_like', type_='foreignkey')
    op.drop_constraint(None, 'user_tips_like', type_='foreignkey')
    op.create_foreign_key(u'user_tips_like_tips_id_fkey', 'user_tips_like', 'tips', ['tips_id'], ['id'])
    op.create_foreign_key(u'user_tips_like_user_id_fkey', 'user_tips_like', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'user_like', type_='foreignkey')
    op.drop_constraint(None, 'user_like', type_='foreignkey')
    op.create_foreign_key(u'user_like_user_id_fkey', 'user_like', 'users', ['user_id'], ['id'])
    op.create_foreign_key(u'user_like_course_id_fkey', 'user_like', 'courses', ['course_id'], ['id'])
    op.drop_constraint(None, 'user_comment_like', type_='foreignkey')
    op.drop_constraint(None, 'user_comment_like', type_='foreignkey')
    op.create_foreign_key(u'user_comment_like_comment_id_fkey', 'user_comment_like', 'comments', ['comment_id'], ['id'])
    op.create_foreign_key(u'user_comment_like_user_id_fkey', 'user_comment_like', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'tags_search', type_='foreignkey')
    op.drop_constraint(None, 'tags_search', type_='foreignkey')
    op.create_foreign_key(u'tags_search_search_id_fkey', 'tags_search', 'search', ['search_id'], ['id'])
    op.create_foreign_key(u'tags_search_tag_id_fkey', 'tags_search', 'tags', ['tag_id'], ['id'])
    op.drop_constraint(None, 'courses_tags', type_='foreignkey')
    op.drop_constraint(None, 'courses_tags', type_='foreignkey')
    op.create_foreign_key(u'courses_tags_tag_id_fkey', 'courses_tags', 'tags', ['tag_id'], ['id'])
    op.create_foreign_key(u'courses_tags_course_id_fkey', 'courses_tags', 'courses', ['course_id'], ['id'])
    op.drop_constraint(None, 'courses_search', type_='foreignkey')
    op.drop_constraint(None, 'courses_search', type_='foreignkey')
    op.create_foreign_key(u'courses_search_course_id_fkey', 'courses_search', 'courses', ['course_id'], ['id'])
    op.create_foreign_key(u'courses_search_search_id_fkey', 'courses_search', 'search', ['search_id'], ['id'])
    ### end Alembic commands ###
