"""empty message

Revision ID: 14d91bb7ff2c
Revises: bd7479b9b120
Create Date: 2016-12-13 17:06:10.257156

"""

# revision identifiers, used by Alembic.
revision = '14d91bb7ff2c'
down_revision = 'bd7479b9b120'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'count')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('count', sa.INTEGER(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
