"""add user avatar

Revision ID: 1d9f0d2bf16c
Revises: None
Create Date: 2016-06-06 20:41:14.069584

"""

# revision identifiers, used by Alembic.
revision = '1d9f0d2bf16c'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar', sa.String(length=200), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar')
    ### end Alembic commands ###
