"""empty message

Revision ID: 7f5f4c9b365f
Revises: 48efeb5840bc
Create Date: 2016-06-09 17:52:30.546172

"""

# revision identifiers, used by Alembic.
revision = '7f5f4c9b365f'
down_revision = '48efeb5840bc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar', sa.String(length=200), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar')
    ### end Alembic commands ###
