"""empty message

Revision ID: bd7479b9b120
Revises: None
Create Date: 2016-11-29 16:30:02.261745

"""

# revision identifiers, used by Alembic.
revision = 'bd7479b9b120'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('available', sa.Boolean(), nullable=True))
    op.add_column('courses', sa.Column('loctime', sa.Text(), nullable=True))
    op.add_column('courses', sa.Column('score', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'score')
    op.drop_column('courses', 'loctime')
    op.drop_column('courses', 'available')
    ### end Alembic commands ###
